### PR TITLE
fix: support vue2 app debugging in micro-app

### LINKED ISSUE #1656: Cannot register multiple vue2 apps in devtools with micro-app
### Version
6.0.0-beta.21

### Browser and OS info
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62

### Steps to reproduce
Here's the repo: https://github.com/DevilTea/reproduce-devtools-micro-app-issue

### What is expected?
Expected to debugging multiple vue2 app with microfrontend framework [micro-app](https://github.com/micro-zoe/micro-app)

### What is actually happening?
The devtools only shows single vue2 App

### PR DESCRIPTION
**Pull request by DevilTea**
closes #1656

### CODE REVIEW

File: packages/app-backend-core/src/legacy/scan.ts [hunk 1]
```diff
@@ -60,6 +60,16 @@ export function scan () {
         // Ignore
       }
     }
+
+    // Scan for Vue instances in the <micro-app> elements
+    const microApps = document.querySelectorAll('micro-app')
```
Comment (Akryum) [inline packages/app-backend-core/src/legacy/scan.ts:65]: We should probably let users configure this selector in case they use something else than micro-app?

Comment (DevilTea) [reply packages/app-backend-core/src/legacy/scan.ts:65]: Oh, that sounds really flexible~
Maybe I could try to put it into GlobalSettings!

Comment (Akryum) [reply packages/app-backend-core/src/legacy/scan.ts]: Maybe it would be better on `window.VUE_DEVTOOLS_CONFIG` since it's specific to each app. Example:
https://devtools.vuejs.org/guide/open-in-editor.html#customize-request

You can probably use `getPageConfig` from `page-config.ts` in backend core

Comment (DevilTea) [reply packages/app-backend-core/src/legacy/scan.ts]: @Akryum I've added it into GlobalSettings. It looks like following images.

image

image

Comment (DevilTea) [reply packages/app-backend-core/src/legacy/scan.ts]: > Maybe it would be better on `window.VUE_DEVTOOLS_CONFIG` since it's specific to each app. Example: https://devtools.vuejs.org/guide/open-in-editor.html#customize-request
> 
> You can probably use `getPageConfig` from `page-config.ts` in backend core

Okay I would try it~ Thank you for your advice!

Comment (DevilTea) [reply packages/app-backend-core/src/legacy/scan.ts]: I have change to use `getPageConfig ` to get the config and add a section in docs to explain the config, it works great to me!

Comment (DevilTea) [reply packages/app-backend-core/src/legacy/scan.ts]: > @Akryum I've added it into GlobalSettings. It looks like following images.
> 
> image
> 
> image

The part of this is removed.

File: packages/app-backend-core/src/legacy/scan.ts [hunk 2]
```diff
@@ -60,6 +61,17 @@ export function scan () {
         // Ignore
       }
     }
+
+    // Scan for Vue instances in the customTarget elements
+    const { customVue2ScanSelector } = getPageConfig() as { customVue2ScanSelector: string }
```
Comment (Akryum) [inline packages/app-backend-core/src/legacy/scan.ts:66]: Could you add the field to the `PageConfig` interface instead of casting?
image

**Review by Akryum — CHANGES_REQUESTED** [review]

File: packages/app-backend-core/src/page-config.ts [hunk 3]
```diff
@@ -3,6 +3,7 @@ import { target, SharedData } from '@vue-devtools/shared-utils'
 export interface PageConfig {
   openInEditorHost?: string
   defaultSelectedAppId?: string
+  customVue2ScanSelector: string
```
Comment (Akryum) [inline packages/app-backend-core/src/page-config.ts:6]:
```suggestion
  customVue2ScanSelector?: string
```

Comment (DevilTea) [reply packages/app-backend-core/src/page-config.ts]: Ok, I've updated!

**Comment by DevilTea** [comment]
Hello @Akryum , is there anything else I need to do?

**Comment by DevilTea** [comment]
Sorry for bothering again, @Akryum would this pr be merged in next release?
Is there anything else I need to do to make this pr be able to be merged?
Thank you~
