### PR TITLE
fix(vue2): Use the super constructor when the instance is a VueComponent

### LINKED ISSUE #1687: Vue2 fails when using a VueComponent instead of Vue as root
### Version
6.0.2

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/gracious-hooks-oicom)

### Steps to reproduce
Use Vue 2
Create a component using `Vue.extend()`
Create an instance of the component using `new` and mount it on the page.
Open Vue dev tools.

### What is expected?
The component can be inspected using Vue dev tools

### What is actually happening?
An exception is thrown
```javascript
Uncaught (in promise) TypeError: options.version is undefined
    registerAppJob backend.js:949
...
```

---
The root cause seems to be in this function.
https://github.com/vuejs/devtools/blob/b3dd744c6ec3a4eeb200b8003e0ff74b9e78abfe/packages/app-backend-core/src/app.ts#L235

In some cases (e.g. `Vue.extend`) `app.constructor` points to `VueComponent` instead of `Vue`. This class does not have a version property.

### PR DESCRIPTION
**Pull request by 0Rick0**
Fixes #1687

### CODE REVIEW

File: packages/app-backend-core/src/app.ts [hunk 1]
```diff
@@ -221,6 +221,14 @@ export async function removeApp (app: App, ctx: BackendContext) {
   }
 }
 
+// eslint-disable-next-line camelcase
+function _legacy_getVueFromApp (app) {
```
Comment (Akryum) [inline packages/app-backend-core/src/app.ts:225]: Could you add a comment explaining why we need to do this? Thanks!

**Review by Akryum — CHANGES_REQUESTED** [review]

**Review by Akryum — APPROVED** [review]

**Review by masstez — APPROVED** [review]
